version: '3.4'
services:
  api:
    image: siontama/lifepoo:latest
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./bin:/app/bin

  db:
    image: mysql:8.0
    container_name: lifepoop-backend-db
    ports:
      - '${DB_PORT}:3306'
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_INITDB_ARGS=--encoding=UTF-8
      - TZ=UTC
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: 'mysqladmin ping -h localhost -u ${DB_USERNAME} --password=${DB_PASSWORD}'
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 0s
    volumes:
      - ./db:/var/lib/mysql
